/*
  reading-vocab.js
  ----------------------------------------------------------------------------
  Word bank for the KOREAN READING COMPREHENSION section only.

  Kept separate from shared-vocab/shared-vocab.js (the main lesson library)
  because that list is already very large. Everything here is beginner-level
  vocabulary that actually appears in the reading stories, their questions, or
  their answer choices.

  Each entry powers the three-level popover hint assistant:
    Level 1 - Meaning        -> entry.en (+ entry.pos)
    Level 2 - How it is used -> entry.usage
    Level 3 - Example        -> entry.exKo / entry.exEn

  Fields
    id       unique slug
    ko       dictionary form in Hangul
    forms    every Hangul surface form that should be underlined in a text
    pos      part of speech
    en       English gloss
    enForms  every English spelling that should be underlined in a translation
    usage    a short note on how the word behaves
    exKo     a model sentence in Hangul
    exEn     the English translation of that sentence

  Romanization is never stored. It is generated by ReadingVocab.romanize(),
  which follows the project's character-by-character transliteration table.
*/
(function (global) {
  "use strict";

  /* =========================================================================
     ROMANIZATION
     Straight character-by-character transliteration. Every syllable block is
     transcribed on its own and syllables are joined with a dash. Letters with
     two readings use the first when they open a syllable and the second when
     they close one.
       ㄱ g/k   ㄴ n   ㄷ d/t   ㄹ r/l   ㅁ m   ㅂ b/p   ㅅ s   ㅇ -/ng
       ㅈ j   ㅊ ch   ㅋ k   ㅌ t   ㅍ p   ㅎ h
       ㄲ gg/kk   ㄸ dd/tt   ㅃ bb/pp   ㅆ ss   ㅉ jj
     No sound-change rules are applied: 좋아해요 becomes joh-a-hae-yo, not
     jo-a-hae-yo, because the goal is to show the spelling.
  ========================================================================= */
  const BASE = 0xAC00;
  const LAST = 0xD7A3;

  // 19 initials, in Unicode order
  const INITIALS = ["g", "gg", "n", "d", "dd", "r", "m", "b", "bb", "s", "ss", "", "j", "jj", "ch", "k", "t", "p", "h"];
  // 21 medials, in Unicode order
  const MEDIALS = ["a", "ae", "ya", "yae", "eo", "e", "yeo", "ye", "o", "oa", "oae", "oi", "yo", "u", "ueo", "ue", "ui", "yu", "eu", "eui", "i"];
  // 28 finals, in Unicode order; index 0 is "no final"
  const FINALS = ["", "k", "kk", "ks", "n", "nj", "nh", "t", "l", "lk", "lm", "lp", "ls", "lt", "lp", "lh", "m", "p", "ps", "s", "ss", "ng", "j", "ch", "k", "t", "p", "h"];

  function isSyllable(ch) {
    const code = ch.codePointAt(0);
    return code >= BASE && code <= LAST;
  }

  function romanizeSyllable(ch) {
    const code = ch.codePointAt(0) - BASE;
    return INITIALS[Math.floor(code / 588)]
      + MEDIALS[Math.floor((code % 588) / 28)]
      + FINALS[code % 28];
  }

  /*
    Romanize a run of text. `carry` lets a caller romanize a string in pieces
    and still get the dash between two syllables that sit either side of a
    piece boundary. Returns { text, endsInSyllable }.
  */
  function romanizeRun(text, carry) {
    let out = "";
    let prev = Boolean(carry);
    for (const ch of String(text ?? "")) {
      if (isSyllable(ch)) {
        out += (prev ? "-" : "") + romanizeSyllable(ch);
        prev = true;
      } else {
        out += ch;
        prev = false;
      }
    }
    return { text: out, endsInSyllable: prev };
  }

  function romanize(text) {
    return romanizeRun(text, false).text;
  }

  /* =========================================================================
     WORD BANK
  ========================================================================= */
  const WORDS = [
    { id: "annyeonghaseyo", ko: "안녕하세요", forms: ["안녕하세요"], pos: "expression", en: "hello", enForms: ["hello"], usage: "The standard polite greeting. It works at any time of day.", exKo: "안녕하세요. 저는 민수예요.", exEn: "Hello. I am Minsu." },
    { id: "ireum", ko: "이름", forms: ["이름", "이름은", "이름이"], pos: "noun", en: "name", enForms: ["name", "name's", "names"], usage: "Often used as 이름은 ... 예요 to say what something is called.", exKo: "제 이름은 유나예요.", exEn: "My name is Yuna." },
    { id: "jeo", ko: "저", forms: ["저는", "저를", "저도", "제"], pos: "pronoun", en: "I, me (polite)", enForms: ["I", "me", "my"], usage: "저 is the humble word for I. Before a noun it becomes 제 (my).", exKo: "저는 학생이에요.", exEn: "I am a student." },
    { id: "haksaeng", ko: "학생", forms: ["학생", "학생이에요", "대학생", "대학생이에요"], pos: "noun", en: "student", enForms: ["student", "students"], usage: "대학생 is a university student. Add 이에요 to say someone is one.", exKo: "언니는 대학생이에요.", exEn: "My older sister is a university student." },
    { id: "hakgyo", ko: "학교", forms: ["학교", "학교에", "학교에서", "학교가", "학교를", "대학교", "대학교에서"], pos: "noun", en: "school", enForms: ["school", "schools"], usage: "Use 학교에 가요 to go to school and 학교에서 to do something at school.", exKo: "아침에 학교에 가요.", exEn: "I go to school in the morning." },
    { id: "gyosil", ko: "교실", forms: ["교실", "교실에"], pos: "noun", en: "classroom", enForms: ["classroom", "classrooms"], usage: "교 is school and 실 is room.", exKo: "교실에 친구가 많아요.", exEn: "There are many friends in the classroom." },
    { id: "ban", ko: "반", forms: ["반", "반이에요"], pos: "noun", en: "class, homeroom", enForms: ["class"], usage: "같은 반 means the same class.", exKo: "우리는 같은 반이에요.", exEn: "We are in the same class." },
    { id: "seonsaengnim", ko: "선생님", forms: ["선생님", "선생님이", "선생님이에요"], pos: "noun", en: "teacher", enForms: ["teacher", "teachers"], usage: "님 is a respectful ending, so 선생님 is always polite.", exKo: "어머니는 선생님이에요.", exEn: "My mother is a teacher." },
    { id: "chingu", ko: "친구", forms: ["친구", "친구를", "친구가", "친구들이", "친구하고"], pos: "noun", en: "friend", enForms: ["friend", "friends"], usage: "Add 들 to make it plural: 친구들.", exKo: "학교에서 친구를 만나요.", exEn: "I meet my friends at school." },
    { id: "gajok", ko: "가족", forms: ["가족", "가족은"], pos: "noun", en: "family", enForms: ["family", "families"], usage: "Counted with 명: 네 명이에요 (there are four).", exKo: "우리 가족은 네 명이에요.", exEn: "My family has four people." },
    { id: "abeoji", ko: "아버지", forms: ["아버지", "아버지는", "아버지하고"], pos: "noun", en: "father", enForms: ["father", "dad"], usage: "The polite word for dad. 아빠 is the casual one.", exKo: "아버지는 의사예요.", exEn: "My father is a doctor." },
    { id: "eomeoni", ko: "어머니", forms: ["어머니", "어머니는", "어머니하고"], pos: "noun", en: "mother", enForms: ["mother", "mom"], usage: "The polite word for mom. 엄마 is the casual one.", exKo: "어머니하고 시장에 가요.", exEn: "I go to the market with my mother." },
    { id: "eonni", ko: "언니", forms: ["언니", "언니는"], pos: "noun", en: "older sister (of a girl)", enForms: ["older sister", "sister"], usage: "A girl says 언니. A boy says 누나.", exKo: "언니는 대학생이에요.", exEn: "My older sister is a university student." },
    { id: "dongsaeng", ko: "동생", forms: ["동생", "동생은", "동생을"], pos: "noun", en: "younger sibling", enForms: ["younger sibling", "younger brother", "sibling"], usage: "One word covers both a younger brother and a younger sister.", exKo: "동생은 그림책을 봐요.", exEn: "My younger sibling looks at a picture book." },
    { id: "uisa", ko: "의사", forms: ["의사", "의사예요"], pos: "noun", en: "doctor", enForms: ["doctor", "doctors"], usage: "Ends in a vowel, so it takes 예요 not 이에요.", exKo: "아버지는 의사예요.", exEn: "My father is a doctor." },
    { id: "saram", ko: "사람", forms: ["사람", "사람이", "사람들"], pos: "noun", en: "person", enForms: ["person", "people"], usage: "한국 사람 means a Korean person.", exKo: "공원에 사람이 없어요.", exEn: "There are no people in the park." },
    { id: "hanguk", ko: "한국", forms: ["한국", "한국어"], pos: "noun", en: "Korea", enForms: ["Korea", "Korean"], usage: "한국 사람 is a Korean person and 한국어 is the Korean language.", exKo: "저는 한국 사람이에요.", exEn: "I am Korean." },
    { id: "jip", ko: "집", forms: ["집", "집에", "집에서"], pos: "noun", en: "house, home", enForms: ["house", "home"], usage: "집에 가요 means to go home.", exKo: "네 시에 집에 가요.", exEn: "I go home at four o'clock." },
    { id: "bang", ko: "방", forms: ["방", "방은", "방이", "방에"], pos: "noun", en: "room", enForms: ["room", "rooms"], usage: "제 방 means my room.", exKo: "제 방은 작아요.", exEn: "My room is small." },
    { id: "chimdae", ko: "침대", forms: ["침대", "침대가"], pos: "noun", en: "bed", enForms: ["bed", "beds"], usage: "침대 옆에 means next to the bed.", exKo: "방에 침대가 있어요.", exEn: "There is a bed in the room." },
    { id: "chaeksang", ko: "책상", forms: ["책상", "책상이", "책상에"], pos: "noun", en: "desk", enForms: ["desk", "desks"], usage: "책 (book) plus 상 (table).", exKo: "침대 옆에 책상이 있어요.", exEn: "There is a desk next to the bed." },
    { id: "uija", ko: "의자", forms: ["의자", "의자가", "의자에"], pos: "noun", en: "chair", enForms: ["chair", "chairs"], usage: "의자에 앉아요 means to sit on a chair.", exKo: "창문 앞에 의자가 있어요.", exEn: "There is a chair in front of the window." },
    { id: "changmun", ko: "창문", forms: ["창문", "창문이"], pos: "noun", en: "window", enForms: ["window", "windows"], usage: "창 alone also means window.", exKo: "창문 앞에 의자가 있어요.", exEn: "There is a chair in front of the window." },
    { id: "chaek", ko: "책", forms: ["책", "책을", "책이", "책은"], pos: "noun", en: "book", enForms: ["book", "books"], usage: "Counted with 권: 두 권 (two books).", exKo: "저는 책을 좋아해요.", exEn: "I like books." },
    { id: "iyagichaek", ko: "이야기책", forms: ["이야기책", "이야기책을"], pos: "noun", en: "story book", enForms: ["story book", "story books"], usage: "이야기 (story) plus 책 (book).", exKo: "저는 이야기책을 읽어요.", exEn: "I read a story book." },
    { id: "geurimchaek", ko: "그림책", forms: ["그림책", "그림책을"], pos: "noun", en: "picture book", enForms: ["picture book", "picture books"], usage: "그림 (picture) plus 책 (book).", exKo: "동생은 그림책을 봐요.", exEn: "My younger sibling looks at a picture book." },
    { id: "gabang", ko: "가방", forms: ["가방", "가방에", "가방이"], pos: "noun", en: "bag", enForms: ["bag", "bags"], usage: "가방에 넣어요 means to put something in a bag.", exKo: "가방에 책을 넣어요.", exEn: "I put a book in my bag." },
    { id: "yeonpil", ko: "연필", forms: ["연필", "연필을", "연필과"], pos: "noun", en: "pencil", enForms: ["pencil", "pencils"], usage: "Joined to another noun with 과 or 하고.", exKo: "가방에 연필을 넣어요.", exEn: "I put a pencil in my bag." },
    { id: "doseogwan", ko: "도서관", forms: ["도서관", "도서관에", "도서관을", "도서관은"], pos: "noun", en: "library", enForms: ["library", "libraries"], usage: "도서관에서 책을 빌려요 means to borrow a book at the library.", exKo: "일요일에 도서관에 가요.", exEn: "On Sunday I go to the library." },
    { id: "sijang", ko: "시장", forms: ["시장", "시장에", "시장에서"], pos: "noun", en: "market", enForms: ["market", "markets"], usage: "시장에서 사요 means to buy at the market.", exKo: "시장에서 사과를 사요.", exEn: "I buy apples at the market." },
    { id: "gongwon", ko: "공원", forms: ["공원", "공원에"], pos: "noun", en: "park", enForms: ["park", "parks"], usage: "공원에 가요 means to go to the park.", exKo: "주말에 공원에 가요.", exEn: "On the weekend we go to the park." },
    { id: "beoseu", ko: "버스", forms: ["버스", "버스를"], pos: "noun", en: "bus", enForms: ["bus", "buses"], usage: "버스를 타요 means to take the bus.", exKo: "버스를 타고 학교에 가요.", exEn: "I take the bus to school." },
    { id: "usan", ko: "우산", forms: ["우산", "우산을", "우산은"], pos: "noun", en: "umbrella", enForms: ["umbrella", "umbrellas"], usage: "비가 올 때 우산을 써요 means you use an umbrella when it rains.", exKo: "우산은 파란색이에요.", exEn: "The umbrella is blue." },
    { id: "namu", ko: "나무", forms: ["나무", "나무가"], pos: "noun", en: "tree", enForms: ["tree", "trees"], usage: "나무 밑에 means under a tree.", exKo: "나무 밑에 새가 있어요.", exEn: "There is a bird under the tree." },
    { id: "sae", ko: "새", forms: ["새", "새가", "새를"], pos: "noun", en: "bird", enForms: ["bird", "birds"], usage: "Animals are counted with 마리: 한 마리 (one animal).", exKo: "새 한 마리가 있어요.", exEn: "There is one bird." },
    { id: "goyangi", ko: "고양이", forms: ["고양이", "고양이를", "고양이도"], pos: "noun", en: "cat", enForms: ["cat", "cats"], usage: "Counted with 마리, like every animal.", exKo: "고양이 이름은 나비예요.", exEn: "The cat's name is Nabi." },
    { id: "gangaji", ko: "강아지", forms: ["강아지", "강아지가", "강아지를"], pos: "noun", en: "puppy, dog", enForms: ["puppy", "puppies", "dog"], usage: "강아지 is a puppy; 개 is the general word for dog.", exKo: "우리 집에 강아지가 있어요.", exEn: "There is a puppy at our house." },
    { id: "haneul", ko: "하늘", forms: ["하늘", "하늘이"], pos: "noun", en: "sky", enForms: ["sky"], usage: "하늘이 어두워요 means the sky is dark.", exKo: "하늘이 어두워요.", exEn: "The sky is dark." },
    { id: "bi", ko: "비", forms: ["비", "비가"], pos: "noun", en: "rain", enForms: ["rain", "raining", "rainy"], usage: "Korean says 비가 와요 (rain comes), not rain falls.", exKo: "오늘은 비가 와요.", exEn: "Today it is raining." },
    { id: "nun", ko: "눈", forms: ["눈", "눈이"], pos: "noun", en: "snow", enForms: ["snow", "snowing"], usage: "Like rain, snow 와요 (comes).", exKo: "겨울에 눈이 와요.", exEn: "It snows in winter." },
    { id: "baram", ko: "바람", forms: ["바람", "바람이"], pos: "noun", en: "wind", enForms: ["wind"], usage: "바람이 불어요 means the wind blows.", exKo: "바람이 불어요.", exEn: "The wind is blowing." },
    { id: "nal", ko: "날", forms: ["날", "날씨", "날씨가", "날도", "날을"], pos: "noun", en: "day, weather", enForms: ["day", "days", "weather"], usage: "날 is a day; 날씨 is the weather.", exKo: "비 오는 날도 예뻐요.", exEn: "A rainy day is pretty too." },
    { id: "achim", ko: "아침", forms: ["아침", "아침에", "아침마다", "아침에는"], pos: "noun", en: "morning", enForms: ["morning", "mornings"], usage: "아침마다 means every morning.", exKo: "아침마다 학교에 가요.", exEn: "Every morning I go to school." },
    { id: "jeomsim", ko: "점심", forms: ["점심", "점심에"], pos: "noun", en: "lunch, midday", enForms: ["lunch", "lunchtime"], usage: "점심 시간 means lunch time.", exKo: "점심 시간에 같이 먹어요.", exEn: "We eat together at lunch time." },
    { id: "jeonyeok", ko: "저녁", forms: ["저녁", "저녁에", "저녁마다"], pos: "noun", en: "evening, dinner", enForms: ["evening", "evenings", "dinner"], usage: "저녁마다 means every evening.", exKo: "저녁마다 산책해요.", exEn: "Every evening I take a walk." },
    { id: "oneul", ko: "오늘", forms: ["오늘", "오늘은"], pos: "noun", en: "today", enForms: ["today"], usage: "Used without 에, unlike most time words.", exKo: "오늘은 비가 와요.", exEn: "Today it is raining." },
    { id: "jumal", ko: "주말", forms: ["주말", "주말에", "주말은", "주말을", "주말마다"], pos: "noun", en: "weekend", enForms: ["weekend", "weekends"], usage: "주말에 means on the weekend.", exKo: "주말은 정말 재미있어요.", exEn: "The weekend is really fun." },
    { id: "toyoil", ko: "토요일", forms: ["토요일", "토요일에", "토요일에는"], pos: "noun", en: "Saturday", enForms: ["Saturday"], usage: "요일 is the ending on every day of the week.", exKo: "토요일에 늦게 일어나요.", exEn: "On Saturday I get up late." },
    { id: "iryoil", ko: "일요일", forms: ["일요일", "일요일에", "일요일에는"], pos: "noun", en: "Sunday", enForms: ["Sunday"], usage: "일 means sun, so 일요일 is sun-day.", exKo: "일요일에 도서관에 가요.", exEn: "On Sunday I go to the library." },
    { id: "si", ko: "시", forms: ["시", "시에", "시간", "시간에"], pos: "counter", en: "o'clock, hour", enForms: ["o'clock", "hour", "time"], usage: "Hours use native numbers: 네 시 (four o'clock).", exKo: "네 시에 집에 가요.", exEn: "I go home at four o'clock." },
    { id: "bun", ko: "분", forms: ["분", "분에"], pos: "counter", en: "minute", enForms: ["minute", "minutes", "thirty"], usage: "Minutes use Sino-Korean numbers: 삼십 분 (thirty minutes).", exKo: "여덟 시 삼십 분이에요.", exEn: "It is eight thirty." },
    { id: "myeong", ko: "명", forms: ["명", "명이에요"], pos: "counter", en: "counter for people", enForms: ["people"], usage: "Used only for counting people: 네 명 (four people).", exKo: "우리 가족은 네 명이에요.", exEn: "My family has four people." },
    { id: "mari", ko: "마리", forms: ["마리", "마리가"], pos: "counter", en: "counter for animals", enForms: ["animal"], usage: "Used only for animals: 한 마리 (one animal).", exKo: "새 한 마리가 있어요.", exEn: "There is one bird." },
    { id: "gwon", ko: "권", forms: ["권", "권을"], pos: "counter", en: "counter for books", enForms: ["volume"], usage: "Used only for books: 두 권 (two books).", exKo: "책을 두 권 빌려요.", exEn: "I borrow two books." },
    { id: "sal", ko: "살", forms: ["살", "살이에요"], pos: "counter", en: "years old", enForms: ["years old"], usage: "Ages use native numbers: 열 살 (ten years old).", exKo: "저는 열 살이에요.", exEn: "I am ten years old." },
    { id: "gada", ko: "가다", forms: ["가요", "가", "가고", "갔어요", "나가요"], pos: "verb", en: "to go", enForms: ["go", "goes", "going", "leave", "leaves"], usage: "The place takes 에: 학교에 가요.", exKo: "저는 도서관에 가요.", exEn: "I go to the library." },
    { id: "oda", ko: "오다", forms: ["와요", "와서", "오는", "옵니다"], pos: "verb", en: "to come", enForms: ["come", "comes", "coming"], usage: "비가 와요 uses this verb to mean it is raining.", exKo: "집에 와서 요리해요.", exEn: "I come home and cook." },
    { id: "itda", ko: "있다", forms: ["있어요", "있는"], pos: "verb", en: "to be, to exist, to have", enForms: ["there is", "there are", "have", "has"], usage: "The thing that exists takes 이/가: 침대가 있어요.", exKo: "방에 침대가 있어요.", exEn: "There is a bed in the room." },
    { id: "eopda", ko: "없다", forms: ["없어요", "없는"], pos: "verb", en: "to not be, to not have", enForms: ["there is no", "there are no", "no people"], usage: "The exact opposite of 있어요.", exKo: "공원에 사람이 없어요.", exEn: "There are no people in the park." },
    { id: "joahada", ko: "좋아하다", forms: ["좋아해요", "좋아하는"], pos: "verb", en: "to like", enForms: ["like", "likes"], usage: "The thing liked takes 을/를: 책을 좋아해요.", exKo: "유나는 김밥을 좋아해요.", exEn: "Yuna likes gimbap." },
    { id: "meokda", ko: "먹다", forms: ["먹어요", "먹는", "먹을"], pos: "verb", en: "to eat", enForms: ["eat", "eats", "eating"], usage: "The food takes 을/를: 밥을 먹어요.", exKo: "우리는 같이 밥을 먹어요.", exEn: "We eat together." },
    { id: "ikda", ko: "읽다", forms: ["읽어요", "읽는"], pos: "verb", en: "to read", enForms: ["read", "reads", "reading"], usage: "The 여 in the spelling is silent in speech but written anyway.", exKo: "저는 이야기책을 읽어요.", exEn: "I read a story book." },
    { id: "boda", ko: "보다", forms: ["봐요", "보세요", "보는"], pos: "verb", en: "to see, to watch, to look at", enForms: ["look at", "looks at", "watch", "watches", "see"], usage: "Covers watching, seeing, and looking at.", exKo: "저는 새를 봐요.", exEn: "I watch the bird." },
    { id: "mannada", ko: "만나다", forms: ["만나요", "만나서"], pos: "verb", en: "to meet", enForms: ["meet", "meets"], usage: "The person met takes 을/를: 친구를 만나요.", exKo: "학교에서 친구를 만나요.", exEn: "I meet my friends at school." },
    { id: "sada", ko: "사다", forms: ["사요", "사는"], pos: "verb", en: "to buy", enForms: ["buy", "buys", "buying"], usage: "The place of buying takes 에서: 시장에서 사요.", exKo: "시장에서 딸기를 사요.", exEn: "I buy strawberries at the market." },
    { id: "mandeulda", ko: "만들다", forms: ["만들어요", "만드는", "만들기"], pos: "verb", en: "to make", enForms: ["make", "makes", "making"], usage: "The ㄹ drops before some endings: 만드는.", exKo: "어머니하고 김밥을 만들어요.", exEn: "I make gimbap with my mother." },
    { id: "yorihada", ko: "요리하다", forms: ["요리해요", "요리를", "요리"], pos: "verb", en: "to cook", enForms: ["cook", "cooks", "cooking"], usage: "요리 is a noun, and 하다 turns it into a verb.", exKo: "집에서 같이 요리해요.", exEn: "We cook together at home." },
    { id: "gongbuhada", ko: "공부하다", forms: ["공부해요", "공부하는", "공부를"], pos: "verb", en: "to study", enForms: ["study", "studies", "studying"], usage: "Same pattern: 공부 plus 하다.", exKo: "언니는 대학교에서 공부해요.", exEn: "My older sister studies at university." },
    { id: "sanchaekhada", ko: "산책하다", forms: ["산책해요", "산책을", "산책"], pos: "verb", en: "to take a walk", enForms: ["take a walk", "takes a walk", "walk"], usage: "The companion takes 하고: 콩이하고 산책해요.", exKo: "저녁마다 산책해요.", exEn: "I take a walk every evening." },
    { id: "geotda", ko: "걷다", forms: ["걸어요", "걸어서", "걷는"], pos: "verb", en: "to walk", enForms: ["walk", "walks", "walking"], usage: "The ㄷ becomes ㄹ before a vowel: 걷다 becomes 걸어요.", exKo: "천천히 걸어요.", exEn: "I walk slowly." },
    { id: "dalrida", ko: "달리다", forms: ["달려요", "달리는"], pos: "verb", en: "to run", enForms: ["run", "runs", "running"], usage: "뛰다 is another common word for run.", exKo: "빨리 달려요.", exEn: "I run fast." },
    { id: "ireonada", ko: "일어나다", forms: ["일어나요", "일어나서"], pos: "verb", en: "to get up, to wake up", enForms: ["get up", "gets up", "wake up", "wakes up"], usage: "The time takes 에: 일곱 시에 일어나요.", exKo: "일곱 시에 일어나요.", exEn: "I get up at seven." },
    { id: "jada", ko: "자다", forms: ["자요", "자는", "잠을"], pos: "verb", en: "to sleep", enForms: ["sleep", "sleeps", "sleeping"], usage: "잠을 자요 is a common set phrase for sleeping.", exKo: "밤에 일찍 자요.", exEn: "I sleep early at night." },
    { id: "tada", ko: "타다", forms: ["타요", "타고"], pos: "verb", en: "to ride, to take (transport)", enForms: ["ride", "rides", "take the bus", "takes the bus"], usage: "The vehicle takes 을/를: 버스를 타요.", exKo: "버스를 타고 가요.", exEn: "I go by bus." },
    { id: "neotda", ko: "넣다", forms: ["넣어요", "넣는"], pos: "verb", en: "to put in", enForms: ["put in", "puts in"], usage: "The container takes 에: 가방에 넣어요.", exKo: "가방에 연필을 넣어요.", exEn: "I put a pencil in my bag." },
    { id: "notda", ko: "놓다", forms: ["놓아요", "놓는"], pos: "verb", en: "to put down, to place", enForms: ["put", "puts", "place", "places"], usage: "The surface takes 에: 접시에 놓아요.", exKo: "접시에 김밥을 놓아요.", exEn: "I put the gimbap on a plate." },
    { id: "billida", ko: "빌리다", forms: ["빌려요", "빌린", "빌리는"], pos: "verb", en: "to borrow", enForms: ["borrow", "borrows", "borrowing"], usage: "The place takes 에서: 도서관에서 빌려요.", exKo: "책을 두 권 빌려요.", exEn: "I borrow two books." },
    { id: "gidarida", ko: "기다리다", forms: ["기다려요", "기다리는"], pos: "verb", en: "to wait", enForms: ["wait", "waits", "waiting"], usage: "The person waited for takes 을/를: 저를 기다려요.", exKo: "친구들이 저를 기다려요.", exEn: "My friends are waiting for me." },
    { id: "deutda", ko: "듣다", forms: ["들어요", "듣는"], pos: "verb", en: "to listen, to hear", enForms: ["listen", "listens", "hear"], usage: "The ㄷ becomes ㄹ before a vowel: 듣다 becomes 들어요.", exKo: "제 이야기를 잘 들어요.", exEn: "He listens to my stories well." },
    { id: "malhada", ko: "말하다", forms: ["말해요", "말하지", "말하는"], pos: "verb", en: "to speak, to say", enForms: ["talk", "talks", "speak", "say"], usage: "말하지 않아요 is the polite way to say do not talk.", exKo: "큰 소리로 말하지 않아요.", exEn: "We do not talk in a loud voice." },
    { id: "nolda", ko: "놀다", forms: ["놀아요", "노는", "놀이"], pos: "verb", en: "to play", enForms: ["play", "plays", "playing"], usage: "놀이 is the noun: 공놀이 is playing with a ball.", exKo: "우리는 매일 같이 놀아요.", exEn: "We play together every day." },
    { id: "jalhada", ko: "잘하다", forms: ["잘해요", "잘"], pos: "verb", en: "to do well, to be good at", enForms: ["well", "good at"], usage: "잘 alone before a verb means well.", exKo: "유나는 노래를 잘해요.", exEn: "Yuna sings well." },
    { id: "jota", ko: "좋다", forms: ["좋아요", "좋은", "좋고"], pos: "adjective", en: "to be good, to be nice", enForms: ["good", "nice", "like"], usage: "좋아요 describes a thing; 좋아해요 describes a person liking it.", exKo: "제 방이 정말 좋아요.", exEn: "I really like my room." },
    { id: "silta", ko: "싫다", forms: ["싫어요", "싫어해요"], pos: "adjective", en: "to be disliked, to hate", enForms: ["dislike", "hate"], usage: "The opposite of 좋아요.", exKo: "저는 비가 싫어요.", exEn: "I dislike the rain." },
    { id: "keuda", ko: "크다", forms: ["커요", "큰", "크고"], pos: "adjective", en: "to be big", enForms: ["big", "large", "loud"], usage: "The ㅡ drops before 어요: 크다 becomes 커요.", exKo: "이 가방은 커요.", exEn: "This bag is big." },
    { id: "jakda", ko: "작다", forms: ["작아요", "작은", "작고"], pos: "adjective", en: "to be small", enForms: ["small", "little"], usage: "The opposite of 커요.", exKo: "제 방은 작아요.", exEn: "My room is small." },
    { id: "manta", ko: "많다", forms: ["많아요", "많은"], pos: "adjective", en: "to be many, to be a lot", enForms: ["many", "a lot", "much"], usage: "The thing counted takes 이/가: 책이 많아요.", exKo: "책상 위에 책이 많아요.", exEn: "There are many books on the desk." },
    { id: "yeppeuda", ko: "예쁘다", forms: ["예뻐요", "예쁜"], pos: "adjective", en: "to be pretty", enForms: ["pretty", "beautiful"], usage: "The ㅡ drops before 어요: 예쁘다 becomes 예뻐요.", exKo: "비 오는 날도 예뻐요.", exEn: "A rainy day is pretty too." },
    { id: "jaemiitda", ko: "재미있다", forms: ["재미있어요", "재미있는", "재미없어요"], pos: "adjective", en: "to be fun, to be interesting", enForms: ["fun", "interesting", "boring"], usage: "재미없어요 is the negative: not fun.", exKo: "주말은 정말 재미있어요.", exEn: "The weekend is really fun." },
    { id: "joyonghada", ko: "조용하다", forms: ["조용해요", "조용한", "조용히"], pos: "adjective", en: "to be quiet", enForms: ["quiet", "quietly"], usage: "조용히 is the adverb: quietly.", exKo: "도서관 안은 조용해요.", exEn: "Inside the library it is quiet." },
    { id: "sikkeureopda", ko: "시끄럽다", forms: ["시끄러워요", "시끄러운"], pos: "adjective", en: "to be noisy", enForms: ["noisy", "loud"], usage: "The opposite of 조용해요.", exKo: "교실이 시끄러워요.", exEn: "The classroom is noisy." },
    { id: "kkaekkeutada", ko: "깨끗하다", forms: ["깨끗해요", "깨끗한", "깨끗하고"], pos: "adjective", en: "to be clean", enForms: ["clean"], usage: "더러워요 is the opposite: dirty.", exKo: "제 방은 깨끗해요.", exEn: "My room is clean." },
    { id: "deoreopda", ko: "더럽다", forms: ["더러워요", "더러운"], pos: "adjective", en: "to be dirty", enForms: ["dirty"], usage: "The ㅂ becomes 워 before 어요: 더럽다 becomes 더러워요.", exKo: "이 신발은 더러워요.", exEn: "These shoes are dirty." },
    { id: "eodupda", ko: "어둡다", forms: ["어두워요", "어두운"], pos: "adjective", en: "to be dark", enForms: ["dark"], usage: "Another ㅂ adjective: 어둡다 becomes 어두워요.", exKo: "하늘이 어두워요.", exEn: "The sky is dark." },
    { id: "balda", ko: "밝다", forms: ["밝아요", "밝은"], pos: "adjective", en: "to be bright", enForms: ["bright"], usage: "The opposite of 어두워요.", exKo: "교실이 밝아요.", exEn: "The classroom is bright." },
    { id: "meolda", ko: "멀다", forms: ["멀어요", "멀지", "먼"], pos: "adjective", en: "to be far", enForms: ["far"], usage: "멀지 않아요 means it is not far.", exKo: "학교는 집에서 멀지 않아요.", exEn: "The school is not far from my house." },
    { id: "gilda", ko: "길다", forms: ["길어요", "긴"], pos: "adjective", en: "to be long", enForms: ["long"], usage: "머리가 길어요 means to have long hair.", exKo: "유나는 머리가 길어요.", exEn: "Yuna has long hair." },
    { id: "jjalda", ko: "짧다", forms: ["짧아요", "짧은"], pos: "adjective", en: "to be short", enForms: ["short"], usage: "The opposite of 길어요.", exKo: "제 머리는 짧아요.", exEn: "My hair is short." },
    { id: "gateun", ko: "같다", forms: ["같은", "같아요", "같이"], pos: "adjective", en: "to be the same", enForms: ["same", "together"], usage: "같이 is the adverb: together.", exKo: "우리는 같은 반이에요.", exEn: "We are in the same class." },
    { id: "dareuda", ko: "다르다", forms: ["달라요", "다른"], pos: "adjective", en: "to be different", enForms: ["different"], usage: "다른 반 means a different class.", exKo: "우리는 다른 반이에요.", exEn: "We are in different classes." },
    { id: "bap", ko: "밥", forms: ["밥", "밥을", "밥이"], pos: "noun", en: "rice, a meal", enForms: ["rice", "meal", "meals"], usage: "밥을 먹어요 can mean to eat rice or simply to eat.", exKo: "아침에 밥을 먹어요.", exEn: "I eat a meal in the morning." },
    { id: "gimbap", ko: "김밥", forms: ["김밥", "김밥을", "김밥이"], pos: "noun", en: "gimbap (rice roll)", enForms: ["gimbap"], usage: "김 (seaweed) plus 밥 (rice).", exKo: "유나는 김밥을 좋아해요.", exEn: "Yuna likes gimbap." },
    { id: "gim", ko: "김", forms: ["김", "김에"], pos: "noun", en: "dried seaweed", enForms: ["seaweed"], usage: "The sheet that gimbap is rolled in.", exKo: "김 위에 밥을 놓아요.", exEn: "I put the rice on the seaweed." },
    { id: "ramyeon", ko: "라면", forms: ["라면", "라면을"], pos: "noun", en: "ramyeon (instant noodles)", enForms: ["ramyeon", "noodles"], usage: "라면을 먹어요 means to eat ramyeon.", exKo: "저는 라면을 좋아해요.", exEn: "I like ramyeon." },
    { id: "sagwa", ko: "사과", forms: ["사과", "사과와", "사과를"], pos: "noun", en: "apple", enForms: ["apple", "apples"], usage: "Joined to another noun with 와 after a vowel.", exKo: "시장에서 사과를 사요.", exEn: "I buy apples at the market." },
    { id: "ttalgi", ko: "딸기", forms: ["딸기", "딸기를"], pos: "noun", en: "strawberry", enForms: ["strawberry", "strawberries"], usage: "Counted with 개: 딸기 세 개.", exKo: "딸기를 좋아해요.", exEn: "I like strawberries." },
    { id: "dangeun", ko: "당근", forms: ["당근", "당근과", "당근을"], pos: "noun", en: "carrot", enForms: ["carrot", "carrots"], usage: "Joined to another noun with 과 after a consonant.", exKo: "당근과 계란을 놓아요.", exEn: "I put carrot and egg on it." },
    { id: "gyeran", ko: "계란", forms: ["계란", "계란을"], pos: "noun", en: "egg", enForms: ["egg", "eggs"], usage: "달걀 is another word for the same thing.", exKo: "계란을 놓아요.", exEn: "I put an egg on it." },
    { id: "uyu", ko: "우유", forms: ["우유", "우유를", "우유와"], pos: "noun", en: "milk", enForms: ["milk"], usage: "Drunk with 마셔요, not 먹어요, in careful speech.", exKo: "우유를 마셔요.", exEn: "I drink milk." },
    { id: "eumsik", ko: "음식", forms: ["음식", "음식은", "음식이"], pos: "noun", en: "food", enForms: ["food", "foods"], usage: "좋아하는 음식 means favourite food.", exKo: "좋아하는 음식은 김밥이에요.", exEn: "My favourite food is gimbap." },
    { id: "jeopsi", ko: "접시", forms: ["접시", "접시에", "접시로"], pos: "noun", en: "plate", enForms: ["plate", "plates"], usage: "접시에 놓아요 means to put something on a plate.", exKo: "접시에 김밥을 놓아요.", exEn: "I put the gimbap on a plate." },
    { id: "kal", ko: "칼", forms: ["칼", "칼로", "칼을"], pos: "noun", en: "knife", enForms: ["knife", "knives"], usage: "칼로 means with a knife; 로 marks the tool.", exKo: "칼로 김밥을 잘라요.", exEn: "I cut the gimbap with a knife." },
    { id: "son", ko: "손", forms: ["손", "손으로", "손을"], pos: "noun", en: "hand", enForms: ["hand", "hands"], usage: "손으로 means with your hands.", exKo: "손으로 먹어요.", exEn: "I eat with my hands." },
    { id: "meori", ko: "머리", forms: ["머리", "머리가", "머리는"], pos: "noun", en: "head, hair", enForms: ["hair", "head"], usage: "머리가 길어요 means to have long hair.", exKo: "유나는 머리가 길어요.", exEn: "Yuna has long hair." },
    { id: "sori", ko: "소리", forms: ["소리", "소리로", "소리가"], pos: "noun", en: "sound, voice", enForms: ["voice", "sound"], usage: "큰 소리로 means in a loud voice.", exKo: "큰 소리로 말하지 않아요.", exEn: "We do not talk in a loud voice." },
    { id: "norae", ko: "노래", forms: ["노래", "노래를"], pos: "noun", en: "song, singing", enForms: ["song", "sing", "sings", "singing"], usage: "노래를 잘해요 means to sing well.", exKo: "유나는 노래를 잘해요.", exEn: "Yuna sings well." },
    { id: "iyagi", ko: "이야기", forms: ["이야기", "이야기를", "이야기는", "이야기예요"], pos: "noun", en: "story, talk", enForms: ["story", "stories"], usage: "이야기를 들어요 means to listen to a story.", exKo: "제 이야기를 잘 들어요.", exEn: "He listens to my stories well." },
    { id: "gong", ko: "공", forms: ["공", "공놀이", "공놀이를"], pos: "noun", en: "ball", enForms: ["ball", "balls"], usage: "공놀이 is playing with a ball.", exKo: "콩이는 공놀이를 좋아해요.", exEn: "Kongi likes playing with a ball." },
    { id: "geurim", ko: "그림", forms: ["그림", "그림을"], pos: "noun", en: "picture, drawing", enForms: ["picture", "pictures", "drawing"], usage: "그림을 그려요 means to draw a picture.", exKo: "그림을 좋아해요.", exEn: "I like pictures." },
    { id: "mulgeon", ko: "물건", forms: ["물건", "물건을"], pos: "noun", en: "thing, goods", enForms: ["thing", "things", "goods"], usage: "물건을 사요 means to buy things.", exKo: "시장에서 물건을 사요.", exEn: "I buy things at the market." },
    { id: "got", ko: "곳", forms: ["곳", "곳이에요"], pos: "noun", en: "place", enForms: ["place", "places"], usage: "Comes after a describing form: 사는 곳 (a place where you buy).", exKo: "물건을 사는 곳이에요.", exEn: "It is a place where you buy things." },
    { id: "pparansaek", ko: "파란색", forms: ["파란색", "파란색이에요"], pos: "noun", en: "blue", enForms: ["blue"], usage: "색 means colour, so 파란색 is the blue colour.", exKo: "우산은 파란색이에요.", exEn: "The umbrella is blue." },
    { id: "ppalgansaek", ko: "빨간색", forms: ["빨간색", "빨간색이에요"], pos: "noun", en: "red", enForms: ["red"], usage: "Same pattern as 파란색.", exKo: "가방은 빨간색이에요.", exEn: "The bag is red." },
    { id: "noransaek", ko: "노란색", forms: ["노란색", "노란색이에요"], pos: "noun", en: "yellow", enForms: ["yellow"], usage: "Same pattern as 파란색.", exKo: "신발은 노란색이에요.", exEn: "The shoes are yellow." },
    { id: "hayansaek", ko: "하얀색", forms: ["하얀색", "하얀색이에요"], pos: "noun", en: "white", enForms: ["white"], usage: "흰색 is another word for white.", exKo: "콩이는 하얀색이에요.", exEn: "Kongi is white." },
    { id: "kkamansaek", ko: "까만색", forms: ["까만색", "까만색이에요"], pos: "noun", en: "black", enForms: ["black"], usage: "검은색 is another word for black.", exKo: "고양이는 까만색이에요.", exEn: "The cat is black." },
    { id: "wi", ko: "위", forms: ["위", "위에"], pos: "noun", en: "top, above", enForms: ["on", "above", "on top of"], usage: "Position words come after the noun: 책상 위에.", exKo: "책상 위에 책이 있어요.", exEn: "There is a book on the desk." },
    { id: "mit", ko: "밑", forms: ["밑", "밑에"], pos: "noun", en: "bottom, under", enForms: ["under", "beneath"], usage: "나무 밑에 means under the tree.", exKo: "나무 밑에 새가 있어요.", exEn: "There is a bird under the tree." },
    { id: "yeop", ko: "옆", forms: ["옆", "옆에"], pos: "noun", en: "side, next to", enForms: ["next to", "beside"], usage: "침대 옆에 means next to the bed.", exKo: "침대 옆에 책상이 있어요.", exEn: "There is a desk next to the bed." },
    { id: "ap", ko: "앞", forms: ["앞", "앞에"], pos: "noun", en: "front", enForms: ["in front of", "front"], usage: "창문 앞에 means in front of the window.", exKo: "창문 앞에 의자가 있어요.", exEn: "There is a chair in front of the window." },
    { id: "dwi", ko: "뒤", forms: ["뒤", "뒤에"], pos: "noun", en: "back, behind", enForms: ["behind", "back"], usage: "학교 뒤에 means behind the school.", exKo: "도서관은 학교 뒤에 있어요.", exEn: "The library is behind the school." },
    { id: "an", ko: "안", forms: ["안", "안은", "안에"], pos: "noun", en: "inside", enForms: ["inside", "in"], usage: "As a separate word 안 before a verb means not.", exKo: "도서관 안은 조용해요.", exEn: "Inside the library it is quiet." },
    { id: "meonjeo", ko: "먼저", forms: ["먼저"], pos: "adverb", en: "first, before anything else", enForms: ["first"], usage: "제일 먼저 means first of all.", exKo: "먼저 밥을 준비해요.", exEn: "First I prepare the rice." },
    { id: "geurigo", ko: "그리고", forms: ["그리고"], pos: "conjunction", en: "and, and then", enForms: ["and then", "then"], usage: "Starts the next sentence in a sequence.", exKo: "그리고 집에 가요.", exEn: "And then I go home." },
    { id: "majimak", ko: "마지막", forms: ["마지막", "마지막에"], pos: "noun", en: "the last one, the end", enForms: ["last", "at the end"], usage: "마지막에 means at the end.", exKo: "마지막에 같이 먹어요.", exEn: "At the end we eat together." },
    { id: "jeil", ko: "제일", forms: ["제일"], pos: "adverb", en: "most, best", enForms: ["best", "most"], usage: "제일 좋은 친구 means best friend.", exKo: "콩이는 제일 좋은 친구예요.", exEn: "Kongi is my best friend." },
    { id: "jeongmal", ko: "정말", forms: ["정말"], pos: "adverb", en: "really", enForms: ["really"], usage: "Goes right before the word it strengthens.", exKo: "제 방이 정말 좋아요.", exEn: "I really like my room." },
    { id: "aju", ko: "아주", forms: ["아주"], pos: "adverb", en: "very", enForms: ["very"], usage: "Like 정말, it goes before an adjective.", exKo: "콩이는 아주 작아요.", exEn: "Kongi is very small." },
    { id: "jogeum", ko: "조금", forms: ["조금"], pos: "adverb", en: "a little", enForms: ["a little", "a little while", "for a little while"], usage: "The opposite of 많이 (a lot).", exKo: "저는 새를 조금 봐요.", exEn: "I watch the bird for a little while." },
    { id: "cheoncheonhi", ko: "천천히", forms: ["천천히"], pos: "adverb", en: "slowly", enForms: ["slowly"], usage: "The opposite of 빨리.", exKo: "김밥을 천천히 말아요.", exEn: "I roll the gimbap slowly." },
    { id: "ppalli", ko: "빨리", forms: ["빨리"], pos: "adverb", en: "quickly, fast", enForms: ["quickly", "fast"], usage: "The opposite of 천천히.", exKo: "빨리 먹어요.", exEn: "I eat quickly." },
    { id: "neutge", ko: "늦게", forms: ["늦게"], pos: "adverb", en: "late", enForms: ["late"], usage: "The opposite of 일찍.", exKo: "토요일에 늦게 일어나요.", exEn: "On Saturday I get up late." },
    { id: "iljjik", ko: "일찍", forms: ["일찍"], pos: "adverb", en: "early", enForms: ["early"], usage: "The opposite of 늦게.", exKo: "일찍 일어나요.", exEn: "I get up early." },
    { id: "maeil", ko: "매일", forms: ["매일"], pos: "adverb", en: "every day", enForms: ["every day"], usage: "매 means every: 매일, 매주, 매년.", exKo: "우리는 매일 같이 놀아요.", exEn: "We play together every day." },
    { id: "gakkeum", ko: "가끔", forms: ["가끔"], pos: "adverb", en: "sometimes", enForms: ["sometimes"], usage: "Less often than 자주 (often).", exKo: "가끔 공원에 가요.", exEn: "Sometimes I go to the park." },
    { id: "hajiman", ko: "하지만", forms: ["하지만"], pos: "conjunction", en: "but, however", enForms: ["but", "however"], usage: "Starts the sentence that contrasts with the one before.", exKo: "작아요. 하지만 깨끗해요.", exEn: "It is small. But it is clean." }
  ];

  /* =========================================================================
     GROUPS
     The word bank is shown grouped, and the vocabulary test lets you pick the
     groups you want. Membership lives here rather than on each entry so the
     word list above stays one line per word.
  ========================================================================= */
  const GROUP_DEFS = [
    { id: "people", label: "사람 · People and family", ids: ["ireum", "jeo", "haksaeng", "seonsaengnim", "chingu", "gajok", "abeoji", "eomeoni", "eonni", "dongsaeng", "uisa", "saram"] },
    { id: "places", label: "장소 · Places", ids: ["hakgyo", "gyosil", "ban", "jip", "bang", "doseogwan", "sijang", "gongwon", "hanguk"] },
    { id: "things", label: "물건 · Things at home and school", ids: ["chimdae", "chaeksang", "uija", "changmun", "chaek", "iyagichaek", "geurimchaek", "gabang", "yeonpil", "beoseu", "usan", "jeopsi", "kal", "gong", "geurim", "mulgeon", "got"] },
    { id: "nature", label: "자연과 동물 · Nature and animals", ids: ["namu", "sae", "goyangi", "gangaji", "haneul", "bi", "nun", "baram", "nal"] },
    { id: "food", label: "음식 · Food and drink", ids: ["bap", "gimbap", "gim", "ramyeon", "sagwa", "ttalgi", "dangeun", "gyeran", "uyu", "eumsik"] },
    { id: "time", label: "시간 · Times and days", ids: ["achim", "jeomsim", "jeonyeok", "oneul", "jumal", "toyoil", "iryoil"] },
    { id: "counters", label: "수와 단위 · Counters", ids: ["si", "bun", "myeong", "mari", "gwon", "sal"] },
    { id: "verbs", label: "동사 · Verbs", ids: ["gada", "oda", "itda", "eopda", "joahada", "meokda", "ikda", "boda", "mannada", "sada", "mandeulda", "yorihada", "gongbuhada", "sanchaekhada", "geotda", "dalrida", "ireonada", "jada", "tada", "neotda", "notda", "billida", "gidarida", "deutda", "malhada", "nolda", "jalhada"] },
    { id: "adjectives", label: "형용사 · Describing words", ids: ["jota", "silta", "keuda", "jakda", "manta", "yeppeuda", "jaemiitda", "joyonghada", "sikkeureopda", "kkaekkeutada", "deoreopda", "eodupda", "balda", "meolda", "gilda", "jjalda", "gateun", "dareuda"] },
    { id: "colours", label: "색과 위치 · Colours and positions", ids: ["pparansaek", "ppalgansaek", "noransaek", "hayansaek", "kkamansaek", "wi", "mit", "yeop", "ap", "dwi", "an"] },
    { id: "expression", label: "말과 몸 · Words, sounds, and the body", ids: ["meori", "son", "sori", "norae", "iyagi"] },
    { id: "small", label: "작은 말 · Little words", ids: ["annyeonghaseyo", "meonjeo", "geurigo", "majimak", "jeil", "jeongmal", "aju", "jogeum", "cheoncheonhi", "ppalli", "neutge", "iljjik", "maeil", "gakkeum", "hajiman"] }
  ];

  const isLatinWordChar = ch => /[A-Za-z'’-]/.test(ch);

  /*
    Generic longest-match scanner.
    `boundary(text, start, end)` decides whether a hit sits on a real word edge.
    Matches never overlap and are returned in reading order.
  */
  function scanWithMap(text, formMap, boundary, lowercase) {
    const source = String(text || "");
    const hay = lowercase ? source.toLowerCase() : source;
    const candidates = [];
    formMap.forEach((entry, form) => candidates.push({ form: lowercase ? form.toLowerCase() : form, entry }));
    candidates.sort((a, b) => b.form.length - a.form.length);

    const taken = new Array(source.length).fill(false);
    const matches = [];
    candidates.forEach(({ form, entry }) => {
      if (!form) return;
      let from = 0;
      while (from <= hay.length - form.length) {
        const start = hay.indexOf(form, from);
        if (start < 0) break;
        const end = start + form.length;
        const free = taken.slice(start, end).every(flag => !flag);
        if (free && boundary(source, start, end)) {
          matches.push({ start, end, entry });
          for (let i = start; i < end; i++) taken[i] = true;
        }
        from = start + Math.max(1, form.length);
      }
    });
    return matches.sort((a, b) => a.start - b.start);
  }

  /* =========================================================================
     BANK FACTORY
     A bank is one word list plus the groups it is displayed in and the two
     scanners built over it. Later grades call this with their own list (plus
     the earlier grade's words, so every word in a passage stays clickable) and
     their own groups.

     options.includeOther — when false, words that no group claims are still
     searchable and clickable but are left out of GROUPS, which is how a later
     grade shows only its own new vocabulary in the tables.
  ========================================================================= */
  function buildBank(words, groupDefs, options) {
    const settings = options || {};
    const byId = new Map(words.map(entry => [entry.id, entry]));

    const koForms = new Map();
    const enForms = new Map();
    words.forEach(entry => {
      new Set([entry.ko, ...(entry.forms || [])]).forEach(form => {
        if (form && !koForms.has(form)) koForms.set(form, entry);
      });
      (entry.enForms || []).forEach(form => {
        const key = String(form).toLowerCase();
        if (key && !enForms.has(key)) enForms.set(key, entry);
      });
    });

    const groups = (groupDefs || []).map(group => ({
      id: group.id,
      label: group.label,
      ids: group.ids.slice()
    }));
    groups.forEach(group => {
      group.ids.forEach(id => {
        const entry = byId.get(id);
        if (entry) {
          entry.group = group.id;
          entry.groupLabel = group.label;
        }
      });
    });

    if (settings.includeOther !== false) {
      /* Anything not listed still gets a home, so a new word is never lost. */
      const other = { id: "other", label: "기타 · Other", ids: [] };
      words.forEach(entry => {
        if (entry.group) return;
        entry.group = other.id;
        entry.groupLabel = other.label;
        other.ids.push(entry.id);
      });
      if (other.ids.length) groups.push(other);
    }

    /*
      Korean: a hit must begin an eojeol, so 이 inside 이름 never lights up, but
      학교 inside 학교에서 does. It may end anywhere, which is what lets a bare
      stem match in front of an attached particle.
    */
    function scanKorean(text) {
      return scanWithMap(text, koForms, (source, start) => {
        const before = start === 0 ? "" : source[start - 1];
        return !before || !isSyllable(before);
      }, false);
    }

    /* English: ordinary letter boundaries on both sides. */
    function scanEnglish(text) {
      return scanWithMap(text, enForms, (source, start, end) => {
        const before = start === 0 ? "" : source[start - 1];
        const after = end >= source.length ? "" : source[end];
        return (!before || !isLatinWordChar(before)) && (!after || !isLatinWordChar(after));
      }, true);
    }

    return {
      WORDS: words,
      GROUPS: groups,
      get: id => byId.get(String(id || "")) || null,
      scanKorean,
      scanEnglish,
      count: words.length
    };
  }

  global.ReadingVocab = Object.assign({
    VERSION: "3.0.0",
    romanize,
    romanizeRun,
    isSyllable,
    buildBank
  }, buildBank(WORDS, GROUP_DEFS));
})(window);
