/*
  reading-vocab-2.js
  ----------------------------------------------------------------------------
  Word bank for the GRADE 2 Korean reading comprehension page.

  Loads on top of reading-vocab.js. The bank it builds contains the grade 1
  words as well, so every word in a grade 2 passage stays clickable, but only
  the grade 2 groups defined here are shown in the word bank tables and offered
  in the vocabulary test. Grade 1 words keep the groups they already had.

  Field shape is identical to reading-vocab.js:
    id, ko, forms, pos, en, enForms, usage, exKo, exEn
  Romanization is generated by ReadingVocab.romanize(), never stored.
*/
(function (global) {
  "use strict";

  const WORDS = [
    /* People, feelings, and the inner life */
    { id: "g2_agi", ko: "아기", forms: ["아기", "아기가", "아기를"], pos: "noun", en: "baby", enForms: ["baby", "babies"], usage: "아기 새 means a baby bird; put 아기 in front of an animal.", exKo: "마당에 아기 새가 있었어요.", exEn: "There was a baby bird in the yard." },
    { id: "g2_bumonim", ko: "부모님", forms: ["부모님", "부모님이", "부모님은"], pos: "noun", en: "parents", enForms: ["parents"], usage: "님 makes it respectful, so it always refers to someone's parents politely.", exKo: "부모님이 마당으로 나왔어요.", exEn: "My parents came out to the yard." },
    { id: "g2_halmeoni", ko: "할머니", forms: ["할머니", "할머니가", "할머니는", "할머니하고", "할머니께서"], pos: "noun", en: "grandmother", enForms: ["grandmother", "grandma"], usage: "께서 is the honorific subject marker used with grandparents.", exKo: "할머니께서 김치를 담그셨어요.", exEn: "My grandmother made kimchi." },
    { id: "g2_onuri", ko: "오누이", forms: ["오누이", "오누이가", "오누이는"], pos: "noun", en: "brother and sister", enForms: ["brother and sister", "siblings"], usage: "An older word for a brother-and-sister pair, common in folk tales.", exKo: "옛날에 오누이가 살았어요.", exEn: "Long ago there lived a brother and a sister." },
    { id: "g2_imgeum", ko: "임금", forms: ["임금", "임금이", "임금님", "임금님이"], pos: "noun", en: "king", enForms: ["king", "kings"], usage: "임금님 with 님 is the respectful form.", exKo: "세종은 훌륭한 임금이었어요.", exEn: "Sejong was a great king." },
    { id: "g2_baekseong", ko: "백성", forms: ["백성", "백성이", "백성들", "백성들이", "백성을"], pos: "noun", en: "the common people", enForms: ["the people", "common people", "people"], usage: "The old word for the ordinary people of a country.", exKo: "백성들이 글자를 배웠어요.", exEn: "The people learned the letters." },
    { id: "g2_maeum", ko: "마음", forms: ["마음", "마음이", "마음을"], pos: "noun", en: "heart, mind, feelings", enForms: ["heart", "mind", "feelings"], usage: "마음이 아파요 means to feel hurt inside.", exKo: "수아의 마음이 따뜻해졌어요.", exEn: "Sua's heart grew warm." },
    { id: "g2_gibun", ko: "기분", forms: ["기분", "기분이", "기분은"], pos: "noun", en: "mood, how you feel", enForms: ["mood", "feel", "feeling"], usage: "기분이 좋아요 means to be in a good mood.", exKo: "수아의 기분이 좋았어요.", exEn: "Sua was in a good mood." },
    { id: "g2_geokjeonghada", ko: "걱정하다", forms: ["걱정했어요", "걱정해요", "걱정이", "걱정을", "걱정"], pos: "verb", en: "to worry", enForms: ["worry", "worried", "worries"], usage: "걱정하지 마세요 means please do not worry.", exKo: "지호는 많이 걱정했어요.", exEn: "Jiho worried a lot." },
    { id: "g2_gippeuda", ko: "기쁘다", forms: ["기뻤어요", "기뻐요", "기뻐했어요", "기쁜"], pos: "adjective", en: "to be glad, to be joyful", enForms: ["glad", "happy", "joyful", "delighted"], usage: "기뻐하다 describes another person showing joy.", exKo: "수아는 정말 기뻤어요.", exEn: "Sua was really glad." },
    { id: "g2_seulpeuda", ko: "슬프다", forms: ["슬펐어요", "슬퍼요", "슬픈"], pos: "adjective", en: "to be sad", enForms: ["sad"], usage: "The ㅡ drops before 어요: 슬프다 becomes 슬퍼요.", exKo: "동생은 조금 슬펐어요.", exEn: "My younger brother was a little sad." },
    { id: "g2_museopda", ko: "무섭다", forms: ["무서웠어요", "무서워요", "무서운"], pos: "adjective", en: "to be scary, to be afraid", enForms: ["scary", "afraid", "frightening", "frightened"], usage: "A ㅂ adjective: 무섭다 becomes 무서워요.", exKo: "호랑이는 정말 무서웠어요.", exEn: "The tiger was really frightening." },
    { id: "g2_nollada", ko: "놀라다", forms: ["놀랐어요", "놀라요", "놀란"], pos: "verb", en: "to be surprised, to be startled", enForms: ["surprised", "startled", "shocked"], usage: "깜짝 놀랐어요 means to get a real fright.", exKo: "지호는 깜짝 놀랐어요.", exEn: "Jiho was startled." },
    { id: "g2_jarangseureopda", ko: "자랑스럽다", forms: ["자랑스러웠어요", "자랑스러워요", "자랑스러운"], pos: "adjective", en: "to be proud", enForms: ["proud"], usage: "Another ㅂ adjective: 자랑스럽다 becomes 자랑스러워요.", exKo: "저는 제 자신이 자랑스러웠어요.", exEn: "I was proud of myself." },
    { id: "g2_mianhada", ko: "미안하다", forms: ["미안했어요", "미안해요", "미안한"], pos: "adjective", en: "to be sorry", enForms: ["sorry"], usage: "죄송하다 is the more formal way to apologise.", exKo: "지호는 사서에게 미안했어요.", exEn: "Jiho felt sorry toward the librarian." },
    { id: "g2_sinnada", ko: "신나다", forms: ["신났어요", "신나요", "신나는"], pos: "verb", en: "to be excited", enForms: ["excited", "exciting"], usage: "Used for happy excitement, like a snow day.", exKo: "우리는 정말 신났어요.", exEn: "We were really excited." },
    { id: "g2_apeuda", ko: "아프다", forms: ["아팠어요", "아파요", "아픈"], pos: "adjective", en: "to hurt, to be sick", enForms: ["hurt", "hurts", "sore", "sick"], usage: "The body part takes 이/가: 무릎이 아파요.", exKo: "무릎이 조금 아팠어요.", exEn: "My knee hurt a little." },

    /* Nature and animals */
    { id: "g2_horangi", ko: "호랑이", forms: ["호랑이", "호랑이가", "호랑이는", "호랑이를"], pos: "noun", en: "tiger", enForms: ["tiger", "tigers"], usage: "The classic villain of Korean folk tales.", exKo: "호랑이가 떡을 달라고 했어요.", exEn: "The tiger asked for a rice cake." },
    { id: "g2_tokki", ko: "토끼", forms: ["토끼", "토끼가", "토끼는", "토끼를"], pos: "noun", en: "rabbit", enForms: ["rabbit", "rabbits", "hare"], usage: "Counted with 마리 like every animal.", exKo: "토끼는 아주 빨랐어요.", exEn: "The rabbit was very fast." },
    { id: "g2_geobugi", ko: "거북이", forms: ["거북이", "거북이가", "거북이는", "거북이를"], pos: "noun", en: "turtle, tortoise", enForms: ["turtle", "tortoise"], usage: "거북 is the shorter dictionary form.", exKo: "거북이는 느리지만 멈추지 않았어요.", exEn: "The tortoise was slow but never stopped." },
    { id: "g2_dungji", ko: "둥지", forms: ["둥지", "둥지에", "둥지에서"], pos: "noun", en: "nest", enForms: ["nest", "nests"], usage: "둥지에서 떨어지다 means to fall out of the nest.", exKo: "아기 새가 둥지에서 떨어졌어요.", exEn: "The baby bird fell out of the nest." },
    { id: "g2_namutgaji", ko: "나뭇가지", forms: ["나뭇가지", "나뭇가지에", "나뭇가지로"], pos: "noun", en: "tree branch", enForms: ["branch", "branches", "tree branch"], usage: "나무 (tree) plus 가지 (branch), with a linking ㅅ.", exKo: "두 새가 나뭇가지로 날아갔어요.", exEn: "The two birds flew to a branch." },
    { id: "g2_nalgae", ko: "날개", forms: ["날개", "날개를", "날개가"], pos: "noun", en: "wing", enForms: ["wing", "wings"], usage: "From 날다 (to fly).", exKo: "새가 날개를 폈어요.", exEn: "The bird spread its wings." },
    { id: "g2_eomi", ko: "어미", forms: ["어미", "어미가", "어미는"], pos: "noun", en: "mother animal", enForms: ["mother bird", "mother animal"], usage: "어미 is used for animals; 어머니 is used for people.", exKo: "어미 새가 가까이에 있었어요.", exEn: "The mother bird was nearby." },
    { id: "g2_hae", ko: "해", forms: ["해", "해가", "해는"], pos: "noun", en: "sun", enForms: ["sun"], usage: "해가 뜨다 means the sun rises.", exKo: "오빠는 해가 되었어요.", exEn: "The brother became the sun." },
    { id: "g2_dal", ko: "달", forms: ["달", "달이", "달은"], pos: "noun", en: "moon", enForms: ["moon"], usage: "해와 달 is the set phrase for sun and moon.", exKo: "동생은 달이 되었어요.", exEn: "The sister became the moon." },
    { id: "g2_sesang", ko: "세상", forms: ["세상", "세상이", "세상은"], pos: "noun", en: "world", enForms: ["world"], usage: "온 세상 means the whole world.", exKo: "온 세상이 하얗게 변했어요.", exEn: "The whole world turned white." },
    { id: "g2_bada", ko: "바다", forms: ["바다", "바다가", "바다를", "바다에"], pos: "noun", en: "sea", enForms: ["sea", "ocean"], usage: "바다에 가다 means to go to the seaside.", exKo: "제주도의 바다는 아주 파랬어요.", exEn: "The sea at Jeju was very blue." },
    { id: "g2_san", ko: "산", forms: ["산", "산이", "산에", "산을"], pos: "noun", en: "mountain", enForms: ["mountain", "mountains"], usage: "산에 오르다 means to climb a mountain.", exKo: "우리는 산에 올랐어요.", exEn: "We climbed the mountain." },
    { id: "g2_seom", ko: "섬", forms: ["섬", "섬이", "섬은", "섬에"], pos: "noun", en: "island", enForms: ["island", "islands"], usage: "제주도 is Korea's largest 섬.", exKo: "제주도는 큰 섬이에요.", exEn: "Jeju is a big island." },

    /* Home, school, and things */
    { id: "g2_madang", ko: "마당", forms: ["마당", "마당에", "마당으로", "마당이"], pos: "noun", en: "yard, courtyard", enForms: ["yard", "courtyard"], usage: "The open ground of a traditional house.", exKo: "마당에 눈이 쌓였어요.", exEn: "Snow piled up in the yard." },
    { id: "g2_daemun", ko: "대문", forms: ["대문", "대문을", "대문이"], pos: "noun", en: "front gate", enForms: ["gate", "front gate", "front door"], usage: "대 (big) plus 문 (door).", exKo: "수아가 대문을 열었어요.", exEn: "Sua opened the front gate." },
    { id: "g2_bueok", ko: "부엌", forms: ["부엌", "부엌에", "부엌에서"], pos: "noun", en: "kitchen", enForms: ["kitchen"], usage: "The final ㅋ is written but sounds like ㄱ.", exKo: "어머니는 부엌에 계셨어요.", exEn: "Mother was in the kitchen." },
    { id: "g2_siktak", ko: "식탁", forms: ["식탁", "식탁에", "식탁 위에"], pos: "noun", en: "dining table", enForms: ["table", "dining table"], usage: "식 (meal) plus 탁 (table).", exKo: "식탁 위에 따뜻한 국이 있었어요.", exEn: "There was warm soup on the table." },
    { id: "g2_changbak", ko: "창밖", forms: ["창밖", "창밖을", "창밖으로"], pos: "noun", en: "outside the window", enForms: ["out the window", "outside the window"], usage: "창 (window) plus 밖 (outside).", exKo: "창밖을 보니 눈이 왔어요.", exEn: "Looking out the window, it had snowed." },
    { id: "g2_undongjang", ko: "운동장", forms: ["운동장", "운동장에", "운동장에서"], pos: "noun", en: "playground, sports field", enForms: ["playground", "field", "sports field"], usage: "운동 (exercise) plus 장 (ground).", exKo: "운동장에 학생들이 모였어요.", exEn: "The students gathered on the field." },
    { id: "g2_undonghoe", ko: "운동회", forms: ["운동회", "운동회가", "운동회는"], pos: "noun", en: "sports day", enForms: ["sports day", "field day"], usage: "A whole-school day of races and games.", exKo: "오늘은 우리 학교 운동회예요.", exEn: "Today is our school sports day." },
    { id: "g2_samulham", ko: "사물함", forms: ["사물함", "사물함에", "사물함을"], pos: "noun", en: "locker, cubby", enForms: ["locker", "cubby"], usage: "The box each student keeps things in at school.", exKo: "책은 사물함에 있었어요.", exEn: "The book was in the locker." },
    { id: "g2_chaekjang", ko: "책장", forms: ["책장", "책장에", "책장을"], pos: "noun", en: "bookshelf", enForms: ["bookshelf", "shelf", "bookcase"], usage: "책 (book) plus 장 (cabinet).", exKo: "책장에서 책을 찾았어요.", exEn: "I looked for the book on the shelf." },
    { id: "g2_seorap", ko: "서랍", forms: ["서랍", "서랍에", "서랍을"], pos: "noun", en: "drawer", enForms: ["drawer", "drawers"], usage: "서랍을 열다 means to open a drawer.", exKo: "서랍도 열어 보았어요.", exEn: "I opened the drawer too." },
    { id: "g2_jajeongeo", ko: "자전거", forms: ["자전거", "자전거를", "자전거가"], pos: "noun", en: "bicycle", enForms: ["bicycle", "bike"], usage: "자전거를 타다 means to ride a bicycle.", exKo: "저는 자전거를 배웠어요.", exEn: "I learned to ride a bicycle." },
    { id: "g2_sseolmae", ko: "썰매", forms: ["썰매", "썰매를", "썰매가"], pos: "noun", en: "sled", enForms: ["sled", "sledding"], usage: "썰매를 타다 means to go sledding.", exKo: "우리는 썰매를 탔어요.", exEn: "We went sledding." },
    { id: "g2_janggap", ko: "장갑", forms: ["장갑", "장갑을", "장갑이"], pos: "noun", en: "gloves", enForms: ["glove", "gloves"], usage: "장갑을 끼다 means to put gloves on.", exKo: "동생이 장갑을 찾았어요.", exEn: "My brother looked for his gloves." },
    { id: "g2_mokdori", ko: "목도리", forms: ["목도리", "목도리를"], pos: "noun", en: "scarf", enForms: ["scarf", "scarves"], usage: "목 (neck) plus 도리 (something wound round).", exKo: "목도리를 하고 나갔어요.", exEn: "I went out wearing a scarf." },
    { id: "g2_nunsaram", ko: "눈사람", forms: ["눈사람", "눈사람을", "눈사람이"], pos: "noun", en: "snowman", enForms: ["snowman", "snowmen"], usage: "눈 (snow) plus 사람 (person).", exKo: "우리는 눈사람을 만들었어요.", exEn: "We made a snowman." },
    { id: "g2_mureup", ko: "무릎", forms: ["무릎", "무릎이", "무릎을"], pos: "noun", en: "knee", enForms: ["knee", "knees"], usage: "무릎이 아파요 means my knee hurts.", exKo: "넘어져서 무릎이 아팠어요.", exEn: "I fell and my knee hurt." },

    /* Food and cooking */
    { id: "g2_kimchi", ko: "김치", forms: ["김치", "김치를", "김치가", "김치는"], pos: "noun", en: "kimchi", enForms: ["kimchi"], usage: "김치를 담그다 is the set phrase for making kimchi.", exKo: "할머니와 김치를 담갔어요.", exEn: "I made kimchi with my grandmother." },
    { id: "g2_baechu", ko: "배추", forms: ["배추", "배추를", "배추가"], pos: "noun", en: "napa cabbage", enForms: ["cabbage", "napa cabbage"], usage: "The main vegetable in kimchi.", exKo: "배추를 소금물에 담갔어요.", exEn: "We soaked the cabbage in salt water." },
    { id: "g2_sogeum", ko: "소금", forms: ["소금", "소금을", "소금물", "소금물에"], pos: "noun", en: "salt", enForms: ["salt", "salt water"], usage: "소금물 is salt water.", exKo: "배추에 소금을 뿌렸어요.", exEn: "We sprinkled salt on the cabbage." },
    { id: "g2_gochutgaru", ko: "고춧가루", forms: ["고춧가루", "고춧가루를"], pos: "noun", en: "chilli powder", enForms: ["chilli powder", "red pepper powder"], usage: "고추 (chilli) plus 가루 (powder), with a linking ㅅ.", exKo: "고춧가루를 많이 넣었어요.", exEn: "We put in a lot of chilli powder." },
    { id: "g2_yangnyeom", ko: "양념", forms: ["양념", "양념을", "양념이"], pos: "noun", en: "seasoning, sauce mix", enForms: ["seasoning", "sauce"], usage: "The mixed paste that flavours a dish.", exKo: "양념을 배추에 발랐어요.", exEn: "We spread the seasoning on the cabbage." },
    { id: "g2_hangari", ko: "항아리", forms: ["항아리", "항아리에", "항아리를"], pos: "noun", en: "clay jar", enForms: ["jar", "clay jar", "pot"], usage: "The big earthenware jar kimchi is stored in.", exKo: "김치를 항아리에 넣었어요.", exEn: "We put the kimchi in a clay jar." },
    { id: "g2_tteok", ko: "떡", forms: ["떡", "떡을", "떡이"], pos: "noun", en: "rice cake", enForms: ["rice cake", "rice cakes"], usage: "A chewy cake made from pounded rice.", exKo: "어머니는 떡을 팔았어요.", exEn: "The mother sold rice cakes." },
    { id: "g2_guk", ko: "국", forms: ["국", "국이", "국을"], pos: "noun", en: "soup", enForms: ["soup"], usage: "국 is served with rice at almost every Korean meal.", exKo: "따뜻한 국을 먹었어요.", exEn: "We ate warm soup." },
    { id: "g2_banchan", ko: "반찬", forms: ["반찬", "반찬을", "반찬이"], pos: "noun", en: "side dish", enForms: ["side dish", "side dishes"], usage: "The small dishes shared around the table.", exKo: "김치는 좋은 반찬이에요.", exEn: "Kimchi is a good side dish." },
    { id: "g2_gyul", ko: "귤", forms: ["귤", "귤을", "귤이"], pos: "noun", en: "tangerine", enForms: ["tangerine", "tangerines"], usage: "Jeju Island is famous for them.", exKo: "제주도에서 귤을 먹었어요.", exEn: "We ate tangerines on Jeju." },
    { id: "g2_maepda", ko: "맵다", forms: ["매워요", "매웠어요", "매운"], pos: "adjective", en: "to be spicy", enForms: ["spicy", "hot"], usage: "A ㅂ adjective: 맵다 becomes 매워요.", exKo: "김치가 조금 매웠어요.", exEn: "The kimchi was a little spicy." },
    { id: "g2_masitda", ko: "맛있다", forms: ["맛있어요", "맛있었어요", "맛있는"], pos: "adjective", en: "to be delicious", enForms: ["delicious", "tasty", "good"], usage: "맛 (taste) plus 있다 (to have).", exKo: "김치가 아주 맛있었어요.", exEn: "The kimchi was very delicious." },

    /* Actions */
    { id: "g2_umjigida", ko: "움직이다", forms: ["움직였어요", "움직여요", "움직이지"], pos: "verb", en: "to move", enForms: ["move", "moved", "moves"], usage: "움직이지 않았어요 means it did not move.", exKo: "새는 움직이지 않았어요.", exEn: "The bird did not move." },
    { id: "g2_sorichida", ko: "소리치다", forms: ["소리쳤어요", "소리쳐요"], pos: "verb", en: "to shout", enForms: ["shout", "shouted", "call", "called"], usage: "소리 (sound) plus 치다 (to strike).", exKo: "수아가 크게 소리쳤어요.", exEn: "Sua shouted loudly." },
    { id: "g2_soksagida", ko: "속삭이다", forms: ["속삭였어요", "속삭여요"], pos: "verb", en: "to whisper", enForms: ["whisper", "whispered"], usage: "The opposite of 소리치다.", exKo: "수아가 조용히 속삭였어요.", exEn: "Sua whispered quietly." },
    { id: "g2_tteoreojida", ko: "떨어지다", forms: ["떨어졌어요", "떨어져요", "떨어진"], pos: "verb", en: "to fall, to drop", enForms: ["fall", "fell", "drop", "dropped"], usage: "The place it fell from takes 에서.", exKo: "아기 새가 둥지에서 떨어졌어요.", exEn: "The baby bird fell from the nest." },
    { id: "g2_jeonhwahada", ko: "전화하다", forms: ["전화했어요", "전화해요", "전화를", "전화"], pos: "verb", en: "to make a phone call", enForms: ["call", "called", "phone", "phoned"], usage: "The person called takes 에게 or 한테.", exKo: "아버지가 센터에 전화했어요.", exEn: "Father called the centre." },
    { id: "g2_doraoda", ko: "돌아오다", forms: ["돌아왔어요", "돌아와요", "돌아온"], pos: "verb", en: "to come back", enForms: ["come back", "came back", "return", "returned"], usage: "돌아가다 is to go back; 돌아오다 is to come back.", exKo: "잠시 후에 아버지가 돌아왔어요.", exEn: "A moment later Father came back." },
    { id: "g2_deryeogada", ko: "데려가다", forms: ["데려가요", "데려갔어요", "데려가지"], pos: "verb", en: "to take (a person or animal) along", enForms: ["take", "took", "take along", "bring"], usage: "Used for living things; 가져가다 is used for objects.", exKo: "새를 집 안으로 데려가지 않았어요.", exEn: "We did not take the bird into the house." },
    { id: "g2_naragada", ko: "날아가다", forms: ["날아갔어요", "날아가요"], pos: "verb", en: "to fly away", enForms: ["fly away", "flew away", "flew"], usage: "날다 (to fly) plus 가다 (to go).", exKo: "두 새가 함께 날아갔어요.", exEn: "The two birds flew away together." },
    { id: "g2_banjjakida", ko: "반짝이다", forms: ["반짝였어요", "반짝여요", "반짝이는"], pos: "verb", en: "to sparkle, to glitter", enForms: ["sparkle", "sparkled", "glitter", "glittered"], usage: "Used for snow, stars, and eyes.", exKo: "온 세상이 반짝였어요.", exEn: "The whole world sparkled." },
    { id: "g2_baeuda", ko: "배우다", forms: ["배웠어요", "배워요", "배우는"], pos: "verb", en: "to learn", enForms: ["learn", "learned", "learns"], usage: "The thing learned takes 을/를.", exKo: "백성들이 한글을 배웠어요.", exEn: "The people learned Hangeul." },
    { id: "g2_sayonghada", ko: "사용하다", forms: ["사용해요", "사용했어요", "사용하는"], pos: "verb", en: "to use", enForms: ["use", "used", "uses"], usage: "쓰다 is the shorter everyday word for the same thing.", exKo: "오늘날에도 한글을 사용해요.", exEn: "We still use Hangeul today." },
    { id: "g2_sogida", ko: "속이다", forms: ["속였어요", "속여요", "속이는"], pos: "verb", en: "to trick, to deceive", enForms: ["trick", "tricked", "deceive", "deceived", "fool"], usage: "The person tricked takes 을/를.", exKo: "호랑이가 오누이를 속였어요.", exEn: "The tiger tricked the brother and sister." },
    { id: "g2_domanggada", ko: "도망가다", forms: ["도망갔어요", "도망가요", "도망쳤어요"], pos: "verb", en: "to run away, to escape", enForms: ["run away", "ran away", "escape", "escaped", "flee"], usage: "도망치다 means the same thing.", exKo: "오누이는 산으로 도망갔어요.", exEn: "The siblings ran away up the mountain." },
    { id: "g2_doeda", ko: "되다", forms: ["되었어요", "돼요", "되는", "됐어요"], pos: "verb", en: "to become", enForms: ["become", "became", "becomes", "turn into"], usage: "What you become takes 이/가, not 을/를.", exKo: "오빠는 해가 되었어요.", exEn: "The brother became the sun." },
    { id: "g2_neomeojida", ko: "넘어지다", forms: ["넘어졌어요", "넘어져요", "넘어지는"], pos: "verb", en: "to fall over, to trip", enForms: ["fall over", "fell over", "trip", "tripped", "fell"], usage: "Used for a person losing their footing.", exKo: "저는 세 번 넘어졌어요.", exEn: "I fell over three times." },
    { id: "g2_ireoseoda", ko: "일어서다", forms: ["일어섰어요", "일어서요"], pos: "verb", en: "to stand up, to get back up", enForms: ["stand up", "stood up", "get up", "got back up"], usage: "일어나다 is to wake up; 일어서다 is to rise to your feet.", exKo: "다시 일어섰어요.", exEn: "I stood back up again." },
    { id: "g2_eungwonhada", ko: "응원하다", forms: ["응원했어요", "응원해요", "응원을", "응원"], pos: "verb", en: "to cheer for", enForms: ["cheer", "cheered", "cheer for", "root for"], usage: "The person cheered for takes 을/를.", exKo: "친구들이 저를 응원했어요.", exEn: "My friends cheered for me." },
    { id: "g2_igida", ko: "이기다", forms: ["이겼어요", "이겨요", "이기는"], pos: "verb", en: "to win", enForms: ["win", "won", "wins", "beat"], usage: "The opponent beaten takes 을/를.", exKo: "우리 반이 이겼어요.", exEn: "Our class won." },
    { id: "g2_jida", ko: "지다", forms: ["졌어요", "져요", "지는"], pos: "verb", en: "to lose", enForms: ["lose", "lost", "loses"], usage: "The opposite of 이기다.", exKo: "토끼가 내기에서 졌어요.", exEn: "The rabbit lost the bet." },
    { id: "g2_ireobeorida", ko: "잃어버리다", forms: ["잃어버렸어요", "잃어버려요", "잃어버린"], pos: "verb", en: "to lose (something)", enForms: ["lose", "lost"], usage: "For misplacing a thing, not for losing a game.", exKo: "지호는 도서관 책을 잃어버렸어요.", exEn: "Jiho lost the library book." },
    { id: "g2_chatda", ko: "찾다", forms: ["찾았어요", "찾아요", "찾는", "찾아서"], pos: "verb", en: "to look for, to find", enForms: ["look for", "looked for", "find", "found", "search"], usage: "One verb covers both searching and finding.", exKo: "지호는 사물함에서 책을 찾았어요.", exEn: "Jiho found the book in his locker." },
    { id: "g2_gieokhada", ko: "기억하다", forms: ["기억했어요", "기억해요", "기억이", "기억"], pos: "verb", en: "to remember", enForms: ["remember", "remembered"], usage: "기억이 나다 means a memory comes back to you.", exKo: "지호는 갑자기 기억했어요.", exEn: "Jiho suddenly remembered." },
    { id: "g2_dollyeojuda", ko: "돌려주다", forms: ["돌려줬어요", "돌려줘요", "돌려주는"], pos: "verb", en: "to give back, to return", enForms: ["give back", "gave back", "return", "returned"], usage: "The person it goes back to takes 에게.", exKo: "책을 도서관에 돌려줬어요.", exEn: "I returned the book to the library." },
    { id: "g2_yeonseuphada", ko: "연습하다", forms: ["연습했어요", "연습해요", "연습을", "연습"], pos: "verb", en: "to practise", enForms: ["practise", "practice", "practised", "practiced"], usage: "매일 연습해요 means to practise every day.", exKo: "저는 매일 연습했어요.", exEn: "I practised every day." },
    { id: "g2_pogihada", ko: "포기하다", forms: ["포기했어요", "포기해요", "포기하지"], pos: "verb", en: "to give up", enForms: ["give up", "gave up", "quit"], usage: "포기하지 않았어요 means did not give up.", exKo: "저는 포기하지 않았어요.", exEn: "I did not give up." },
    { id: "g2_oreuda", ko: "오르다", forms: ["올랐어요", "올라요", "오르는", "올라갔어요"], pos: "verb", en: "to climb, to go up", enForms: ["climb", "climbed", "go up", "went up"], usage: "The place climbed takes 에: 산에 올랐어요.", exKo: "우리는 산에 올랐어요.", exEn: "We climbed the mountain." },
    { id: "g2_jjikda", ko: "찍다", forms: ["찍었어요", "찍어요", "찍는"], pos: "verb", en: "to take (a photo)", enForms: ["take a photo", "took a photo", "photograph"], usage: "사진을 찍다 is the set phrase for taking a picture.", exKo: "바다에서 사진을 찍었어요.", exEn: "We took photos at the sea." },
    { id: "g2_swida", ko: "쉬다", forms: ["쉬었어요", "쉬어요", "쉬는"], pos: "verb", en: "to rest", enForms: ["rest", "rested", "take a break"], usage: "잠깐 쉬다 means to take a short rest.", exKo: "토끼는 나무 밑에서 쉬었어요.", exEn: "The rabbit rested under a tree." },
    { id: "g2_dochakhada", ko: "도착하다", forms: ["도착했어요", "도착해요", "도착한"], pos: "verb", en: "to arrive", enForms: ["arrive", "arrived", "reach", "reached"], usage: "The place takes 에: 학교에 도착했어요.", exKo: "거북이가 먼저 도착했어요.", exEn: "The tortoise arrived first." },
    { id: "g2_yeolda", ko: "열다", forms: ["열었어요", "열어요", "여는", "열어서"], pos: "verb", en: "to open", enForms: ["open", "opened", "opens"], usage: "닫다 is the opposite: to close.", exKo: "수아가 대문을 열었어요.", exEn: "Sua opened the gate." },
    { id: "g2_saenggakhada", ko: "생각하다", forms: ["생각했어요", "생각해요", "생각이", "생각"], pos: "verb", en: "to think", enForms: ["think", "thought", "thinks"], usage: "생각이 나다 means something comes to mind.", exKo: "저는 잠시 생각했어요.", exEn: "I thought for a moment." },

    /* Describing words */
    { id: "g2_hayata", ko: "하얗다", forms: ["하얬어요", "하얀", "하얗게"], pos: "adjective", en: "to be white", enForms: ["white"], usage: "하얗게 is the adverb form: whitely.", exKo: "온 세상이 하얬어요.", exEn: "The whole world was white." },
    { id: "g2_ttatteutada", ko: "따뜻하다", forms: ["따뜻했어요", "따뜻해요", "따뜻한"], pos: "adjective", en: "to be warm", enForms: ["warm"], usage: "Used for weather, food, and kind feelings alike.", exKo: "따뜻한 국이 있었어요.", exEn: "There was warm soup." },
    { id: "g2_eoryeopda", ko: "어렵다", forms: ["어려웠어요", "어려워요", "어려운"], pos: "adjective", en: "to be difficult", enForms: ["difficult", "hard"], usage: "A ㅂ adjective: 어렵다 becomes 어려워요.", exKo: "옛날 글자는 아주 어려웠어요.", exEn: "The old letters were very difficult." },
    { id: "g2_swipda", ko: "쉽다", forms: ["쉬웠어요", "쉬워요", "쉬운"], pos: "adjective", en: "to be easy", enForms: ["easy"], usage: "The opposite of 어렵다.", exKo: "한글은 배우기 쉬워요.", exEn: "Hangeul is easy to learn." },
    { id: "g2_hullyunghada", ko: "훌륭하다", forms: ["훌륭했어요", "훌륭해요", "훌륭한"], pos: "adjective", en: "to be excellent, to be great", enForms: ["great", "excellent", "fine"], usage: "Used to praise a person or a piece of work.", exKo: "세종은 훌륭한 임금이었어요.", exEn: "Sejong was a great king." },
    { id: "g2_ppareuda", ko: "빠르다", forms: ["빨랐어요", "빨라요", "빠른"], pos: "adjective", en: "to be fast", enForms: ["fast", "quick"], usage: "An irregular 르 stem: 빠르다 becomes 빨라요.", exKo: "토끼는 아주 빨랐어요.", exEn: "The rabbit was very fast." },
    { id: "g2_neurida", ko: "느리다", forms: ["느렸어요", "느려요", "느린"], pos: "adjective", en: "to be slow", enForms: ["slow"], usage: "The opposite of 빠르다.", exKo: "거북이는 느렸어요.", exEn: "The tortoise was slow." },
    { id: "g2_himdeulda", ko: "힘들다", forms: ["힘들었어요", "힘들어요", "힘든"], pos: "adjective", en: "to be hard, to be tiring", enForms: ["hard", "tiring", "tough"], usage: "About effort, while 어렵다 is about difficulty.", exKo: "달리기는 힘들었어요.", exEn: "The race was tiring." },
    { id: "g2_yumyeonghada", ko: "유명하다", forms: ["유명했어요", "유명해요", "유명한"], pos: "adjective", en: "to be famous", enForms: ["famous", "well known"], usage: "What it is famous for takes 으로.", exKo: "제주도는 귤로 유명해요.", exEn: "Jeju is famous for tangerines." },
    { id: "g2_teukbyeolhada", ko: "특별하다", forms: ["특별했어요", "특별해요", "특별한"], pos: "adjective", en: "to be special", enForms: ["special"], usage: "특별히 is the adverb: especially.", exKo: "아주 특별한 날이었어요.", exEn: "It was a very special day." },
    { id: "g2_georeuda", ko: "게으르다", forms: ["게을렀어요", "게을러요", "게으른"], pos: "adjective", en: "to be lazy", enForms: ["lazy"], usage: "Another 르 stem: 게으르다 becomes 게을러요.", exKo: "토끼는 게을렀어요.", exEn: "The rabbit was lazy." },
    { id: "g2_kkujunhi", ko: "꾸준히", forms: ["꾸준히"], pos: "adverb", en: "steadily, without stopping", enForms: ["steadily", "without stopping", "keep going"], usage: "The adverb of 꾸준하다 (to be steady).", exKo: "거북이는 꾸준히 걸었어요.", exEn: "The tortoise walked steadily." },
    { id: "g2_neutda", ko: "늦다", forms: ["늦었어요", "늦어요", "늦은"], pos: "adjective", en: "to be late", enForms: ["late"], usage: "Also a verb: 늦었어요 can mean I was late.", exKo: "책을 늦게 돌려줬어요.", exEn: "I returned the book late." },

    /* Time and order */
    { id: "g2_yetnal", ko: "옛날", forms: ["옛날", "옛날에", "옛날이야기"], pos: "noun", en: "long ago, the old days", enForms: ["long ago", "the old days", "once upon a time"], usage: "옛날 옛날에 is how Korean folk tales begin.", exKo: "옛날에 오누이가 살았어요.", exEn: "Long ago there lived a brother and sister." },
    { id: "g2_oneulnal", ko: "오늘날", forms: ["오늘날", "오늘날에도", "오늘날에는"], pos: "noun", en: "nowadays, today", enForms: ["nowadays", "today", "these days"], usage: "About the present era, unlike 오늘 (this one day).", exKo: "오늘날에도 한글을 써요.", exEn: "We still use Hangeul nowadays." },
    { id: "g2_bamsae", ko: "밤새", forms: ["밤새", "밤새에"], pos: "adverb", en: "overnight, all night", enForms: ["overnight", "all night", "during the night"], usage: "밤 (night) plus 새 (through).", exKo: "밤새 눈이 왔어요.", exEn: "It snowed overnight." },
    { id: "g2_jamsi", ko: "잠시", forms: ["잠시", "잠시 후에", "잠깐"], pos: "adverb", en: "for a moment", enForms: ["for a moment", "a moment", "briefly"], usage: "잠시 후에 means a moment later.", exKo: "잠시 후에 아버지가 돌아왔어요.", exEn: "A moment later Father came back." },
    { id: "g2_geuttae", ko: "그때", forms: ["그때", "그때에"], pos: "adverb", en: "at that moment, then", enForms: ["at that moment", "then", "just then"], usage: "Points back to a moment already mentioned.", exKo: "그때 새가 입을 벌렸어요.", exEn: "Just then the bird opened its beak." },
    { id: "g2_gapjagi", ko: "갑자기", forms: ["갑자기"], pos: "adverb", en: "suddenly", enForms: ["suddenly", "all of a sudden"], usage: "Goes near the front of the sentence.", exKo: "갑자기 기억이 났어요.", exEn: "Suddenly I remembered." },
    { id: "g2_deudieo", ko: "드디어", forms: ["드디어"], pos: "adverb", en: "finally, at last", enForms: ["finally", "at last"], usage: "Used when something long awaited happens.", exKo: "드디어 혼자 탈 수 있었어요.", exEn: "At last I could ride on my own." },
    { id: "g2_cheoeum", ko: "처음", forms: ["처음", "처음에", "처음으로"], pos: "noun", en: "the first time, the beginning", enForms: ["first", "the first time", "at first", "beginning"], usage: "처음에 means at first; 처음으로 means for the first time.", exKo: "처음에는 무서웠어요.", exEn: "At first I was scared." },
    { id: "g2_dasi", ko: "다시", forms: ["다시"], pos: "adverb", en: "again", enForms: ["again"], usage: "다시 한번 means one more time.", exKo: "저는 다시 일어섰어요.", exEn: "I stood up again." },
    { id: "g2_hamkke", ko: "함께", forms: ["함께"], pos: "adverb", en: "together", enForms: ["together"], usage: "A slightly more formal 같이.", exKo: "두 새가 함께 날아갔어요.", exEn: "The two birds flew away together." },
    { id: "g2_honja", ko: "혼자", forms: ["혼자", "혼자서"], pos: "adverb", en: "alone, by oneself", enForms: ["alone", "by myself", "on my own"], usage: "혼자서 adds a little emphasis.", exKo: "드디어 혼자 탔어요.", exEn: "At last I rode by myself." },
    { id: "g2_gakkai", ko: "가까이", forms: ["가까이", "가까이에", "가까운"], pos: "adverb", en: "nearby, close", enForms: ["nearby", "close", "near"], usage: "The adverb of 가깝다 (to be close).", exKo: "어미 새가 가까이에 있었어요.", exEn: "The mother bird was nearby." },
    { id: "g2_gyeoul", ko: "겨울", forms: ["겨울", "겨울에", "겨울이"], pos: "noun", en: "winter", enForms: ["winter"], usage: "The four seasons are 봄, 여름, 가을, 겨울.", exKo: "겨울에 김치를 먹어요.", exEn: "We eat kimchi in winter." },

    /* Connecting words */
    { id: "g2_geuraeseo", ko: "그래서", forms: ["그래서"], pos: "conjunction", en: "so, that is why", enForms: ["so", "that is why", "and so"], usage: "Starts the sentence that gives the result.", exKo: "비가 왔어요. 그래서 집에 있었어요.", exEn: "It rained. So we stayed home." },
    { id: "g2_geureonde", ko: "그런데", forms: ["그런데"], pos: "conjunction", en: "but, by the way", enForms: ["but", "however", "by the way"], usage: "Softer than 하지만; often introduces a surprise.", exKo: "그런데 책이 없었어요.", exEn: "But the book was not there." },
    { id: "g2_waenyahamyeon", ko: "왜냐하면", forms: ["왜냐하면"], pos: "conjunction", en: "because", enForms: ["because", "the reason is"], usage: "The sentence it starts usually ends with 때문이에요.", exKo: "왜냐하면 눈이 왔기 때문이에요.", exEn: "That is because it snowed." },
    { id: "g2_tto", ko: "또", forms: ["또"], pos: "adverb", en: "again, also", enForms: ["again", "also", "too"], usage: "Shorter and more casual than 다시.", exKo: "또 넘어졌어요.", exEn: "I fell over again." },
    { id: "g2_dahaeng", ko: "다행", forms: ["다행", "다행이에요", "다행이야", "다행히"], pos: "noun", en: "a relief, luckily", enForms: ["a relief", "luckily", "fortunately"], usage: "다행이에요 means what a relief.", exKo: "정말 다행이에요.", exEn: "What a relief." },

    /* Words for talking about stories */
    { id: "g2_juingong", ko: "주인공", forms: ["주인공", "주인공이", "주인공은"], pos: "noun", en: "main character", enForms: ["main character", "hero"], usage: "The person a story is mainly about.", exKo: "이 글의 주인공은 수아예요.", exEn: "The main character of this passage is Sua." },
    { id: "g2_jemok", ko: "제목", forms: ["제목", "제목이", "제목으로", "제목은"], pos: "noun", en: "title", enForms: ["title", "titles"], usage: "제목으로 알맞은 것 means the most suitable title.", exKo: "이 글의 제목은 무엇이에요?", exEn: "What is the title of this passage?" },
    { id: "g2_kkadalk", ko: "까닭", forms: ["까닭", "까닭은", "까닭이"], pos: "noun", en: "reason", enForms: ["reason", "why"], usage: "A slightly literary word for 이유.", exKo: "그 까닭은 무엇이에요?", exEn: "What is the reason for that?" },
    { id: "g2_sasil", ko: "사실", forms: ["사실", "사실이", "사실은"], pos: "noun", en: "a fact, actually", enForms: ["fact", "facts", "real", "true"], usage: "사실 at the start of a sentence means actually.", exKo: "이것은 사실이에요.", exEn: "This is a fact." },
    { id: "g2_sangsang", ko: "상상", forms: ["상상", "상상이", "상상한"], pos: "noun", en: "imagination, make-believe", enForms: ["imagination", "make-believe", "imagined"], usage: "상상하다 means to imagine.", exKo: "그것은 상상이에요.", exEn: "That is make-believe." },
    { id: "g2_geul", ko: "글", forms: ["글", "글이", "글은", "글자", "글자를", "글자가"], pos: "noun", en: "writing, a passage", enForms: ["passage", "writing", "text", "letters"], usage: "글자 means a written character.", exKo: "이 글은 무엇에 대한 글이에요?", exEn: "What is this passage about?" },
    { id: "g2_gyohun", ko: "교훈", forms: ["교훈", "교훈은", "교훈이"], pos: "noun", en: "lesson, moral", enForms: ["lesson", "moral"], usage: "The point a fable teaches.", exKo: "이 이야기의 교훈은 무엇이에요?", exEn: "What is the moral of this story?" },
    { id: "g2_naegi", ko: "내기", forms: ["내기", "내기를", "내기에서"], pos: "noun", en: "a bet, a contest", enForms: ["bet", "race", "contest"], usage: "내기를 하다 means to make a bet.", exKo: "토끼와 거북이가 내기를 했어요.", exEn: "The rabbit and the tortoise made a bet." },
    { id: "g2_hangeul", ko: "한글", forms: ["한글", "한글을", "한글이", "한글은"], pos: "noun", en: "Hangeul (the Korean alphabet)", enForms: ["Hangeul", "Korean alphabet"], usage: "The writing system, as opposed to 한국어, the language.", exKo: "세종대왕이 한글을 만들었어요.", exEn: "King Sejong created Hangeul." },
    { id: "g2_yeohaeng", ko: "여행", forms: ["여행", "여행을", "여행이", "여행했어요"], pos: "noun", en: "a trip, travel", enForms: ["trip", "travel", "journey"], usage: "여행을 가다 means to go on a trip.", exKo: "제주도로 여행을 갔어요.", exEn: "We took a trip to Jeju." },
    { id: "g2_sajin", ko: "사진", forms: ["사진", "사진을", "사진이"], pos: "noun", en: "photograph", enForms: ["photo", "photos", "photograph", "picture"], usage: "사진을 찍다 means to take a photo.", exKo: "사진을 많이 찍었어요.", exEn: "We took a lot of photos." },
    { id: "g2_bihaenggi", ko: "비행기", forms: ["비행기", "비행기를", "비행기가"], pos: "noun", en: "aeroplane", enForms: ["plane", "airplane", "aeroplane"], usage: "비행기를 타다 means to take a plane.", exKo: "비행기를 타고 갔어요.", exEn: "We went by plane." }
  ];

  const GROUP_DEFS = [
    { id: "g2_people", label: "사람과 마음 · People and feelings", ids: ["g2_agi", "g2_bumonim", "g2_halmeoni", "g2_onuri", "g2_imgeum", "g2_baekseong", "g2_maeum", "g2_gibun", "g2_geokjeonghada", "g2_gippeuda", "g2_seulpeuda", "g2_museopda", "g2_nollada", "g2_jarangseureopda", "g2_mianhada", "g2_sinnada", "g2_apeuda"] },
    { id: "g2_nature", label: "자연과 동물 · Nature and animals", ids: ["g2_horangi", "g2_tokki", "g2_geobugi", "g2_dungji", "g2_namutgaji", "g2_nalgae", "g2_eomi", "g2_hae", "g2_dal", "g2_sesang", "g2_bada", "g2_san", "g2_seom"] },
    { id: "g2_places", label: "집과 학교 · Home, school, and things", ids: ["g2_madang", "g2_daemun", "g2_bueok", "g2_siktak", "g2_changbak", "g2_undongjang", "g2_undonghoe", "g2_samulham", "g2_chaekjang", "g2_seorap", "g2_jajeongeo", "g2_sseolmae", "g2_janggap", "g2_mokdori", "g2_nunsaram", "g2_mureup"] },
    { id: "g2_food", label: "음식과 요리 · Food and cooking", ids: ["g2_kimchi", "g2_baechu", "g2_sogeum", "g2_gochutgaru", "g2_yangnyeom", "g2_hangari", "g2_tteok", "g2_guk", "g2_banchan", "g2_gyul", "g2_maepda", "g2_masitda"] },
    { id: "g2_actions", label: "움직임 · Actions", ids: ["g2_umjigida", "g2_sorichida", "g2_soksagida", "g2_tteoreojida", "g2_jeonhwahada", "g2_doraoda", "g2_deryeogada", "g2_naragada", "g2_banjjakida", "g2_baeuda", "g2_sayonghada", "g2_sogida", "g2_domanggada", "g2_doeda", "g2_neomeojida", "g2_ireoseoda", "g2_eungwonhada", "g2_igida", "g2_jida", "g2_ireobeorida", "g2_chatda", "g2_gieokhada", "g2_dollyeojuda", "g2_yeonseuphada", "g2_pogihada", "g2_oreuda", "g2_jjikda", "g2_swida", "g2_dochakhada", "g2_yeolda", "g2_saenggakhada"] },
    { id: "g2_describing", label: "모습 · Describing words", ids: ["g2_hayata", "g2_ttatteutada", "g2_eoryeopda", "g2_swipda", "g2_hullyunghada", "g2_ppareuda", "g2_neurida", "g2_himdeulda", "g2_yumyeonghada", "g2_teukbyeolhada", "g2_georeuda", "g2_kkujunhi", "g2_neutda"] },
    { id: "g2_time", label: "시간과 순서 · Time and order", ids: ["g2_yetnal", "g2_oneulnal", "g2_bamsae", "g2_jamsi", "g2_geuttae", "g2_gapjagi", "g2_deudieo", "g2_cheoeum", "g2_dasi", "g2_hamkke", "g2_honja", "g2_gakkai", "g2_gyeoul"] },
    { id: "g2_connect", label: "이어 주는 말 · Connecting words", ids: ["g2_geuraeseo", "g2_geureonde", "g2_waenyahamyeon", "g2_tto", "g2_dahaeng"] },
    { id: "g2_story", label: "이야기 말 · Words for talking about stories", ids: ["g2_juingong", "g2_jemok", "g2_kkadalk", "g2_sasil", "g2_sangsang", "g2_geul", "g2_gyohun", "g2_naegi", "g2_hangeul", "g2_yeohaeng", "g2_sajin", "g2_bihaenggi"] }
  ];

  /*
    The bank scans grade 1 words too, so anything a passage reuses from the
    earlier level still opens a popover. includeOther is false so those grade 1
    words stay out of this page's tables and vocabulary test.
  */
  const base = global.ReadingVocab;
  const allWords = base && base.WORDS ? base.WORDS.concat(WORDS) : WORDS;

  global.ReadingVocab2 = Object.assign({
    VERSION: "1.0.0",
    NEW_WORDS: WORDS,
    romanize: base.romanize,
    romanizeRun: base.romanizeRun,
    isSyllable: base.isSyllable
  }, base.buildBank(allWords, GROUP_DEFS, { includeOther: false }));
})(window);
